run part:
    cargo run --bin part-{{part}} --release
build part:
    cargo build --bin part-{{part}} --release
bench part:
    cargo bench --bench part_{{part}}
test part:
    cargo watch -x "nextest run part_{{part}}" --clear
